In [1]:
import numpy as np

In [ ]:
#1
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#2
a = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
#3
matrix = np.random.randint(1, 11, 5)
print(matrix)

[10  4  9 10  7]


In [12]:
#4
matrix2 = np.random.rand(4, 4)
print(matrix2)

[[0.74340369 0.99157143 0.80933262 0.32572148]
 [0.47334225 0.79274797 0.01994516 0.93142945]
 [0.5822564  0.80647399 0.29225673 0.67537244]
 [0.88386657 0.83472458 0.69050055 0.39525305]]


In [ ]:
'''
5. Створіть два одновимірних масиви розміром 5, заповніть їх 
випадковими цілими числами в діапазоні від 1 до 10  та 
виконайте на них поелементні операції додавання, віднімання та множення.
'''

array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

add = array1 + array2
substract = array1 - array2
multiply = array1 * array2

print(array1, array2)
print(add, substract, multiply)

[ 3  3  1  2 10] [8 7 9 7 5]
[11 10 10  9 15] [-5 -4 -8 -5  5] [24 21  9 14 50]


In [17]:
'''
6. Створіть два вектори розміром 7, заповніть довільними 
числами та знайдіть їх скалярний добуток.
'''

vector1 = [5, 66, 83, 12, 58, 34, 8]
vector2 = [32, 15, 63, 11, 3, 5, 13]

print(np.dot(vector1, vector2))  

6959


In [19]:
'''
7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими 
цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
'''

matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3)) 

print("Матриця 1: \n", matrix_1)
print("\n Матриця 2: \n", matrix_2)
print("\n Матриця 1 * Матриця 2: \n", np.matmul(matrix_1, matrix_2))

Матриця 1: 
 [[3 1]
 [9 8]]

 Матриця 2: 
 [[ 3 10  1]
 [ 3  6  9]]

 Матриця 1 * Матриця 2: 
 [[ 12  36  12]
 [ 51 138  81]]


In [26]:
'''
8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами 
в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
'''

matrix_a = np.random.randint(1, 11, (3, 3))
matrix_b = matrix_a.T

print(f'Матриця а: \n{matrix_a}')
print(f'\n Матриця, обернена до неї: \n{matrix_b}')  

Матриця а: 
[[ 8  6  2]
 [10  3  8]
 [ 1  5  6]]

 Матриця, обернена до неї: 
[[ 8 10  1]
 [ 6  3  5]
 [ 2  8  6]]


In [27]:
'''
9. Створіть матрицю розміром 4x4, заповніть її випадковими 
дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
'''

matrix_a = np.random.rand(4, 4)
matrix_b = matrix_a.T

print(f'Матриця а: \n{matrix_a}')
print(f'\n Матриця, обернена до неї: \n{matrix_b}') 

Матриця а: 
[[0.38761665 0.55611874 0.93117807 0.09986932]
 [0.9726411  0.58484208 0.10689081 0.4050723 ]
 [0.23321575 0.85105399 0.84088898 0.04981226]
 [0.04929601 0.09531524 0.89643972 0.42109186]]

 Матриця, обернена до неї: 
[[0.38761665 0.9726411  0.23321575 0.04929601]
 [0.55611874 0.58484208 0.85105399 0.09531524]
 [0.93117807 0.10689081 0.84088898 0.89643972]
 [0.09986932 0.4050723  0.04981226 0.42109186]]


In [ ]:
'''
10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх 
випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
'''
matrix10 = np.random.randint(1, 11, (3, 4))
vector10 = np.random.randint(1, 11, 4)

print("Матриця:")
print(matrix10)
print("\nВектор:")
print(vector10)

print("\nМноження матриці на вектор:")
print(np.matmul(matrix10, vector10))



Матриця:
[[ 2 10  6 10]
 [ 7  7  8 10]
 [10  7  2  8]]

Вектор:
[ 2 10  3 10]

Результат перемноження матриці на вектор:
[222 208 176]


In [30]:
'''
11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими 
дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
'''

matrix11 = np.random.rand(2, 3)
vector11 = np.random.rand(3)

print("Матриця:")
print(matrix11)
print("\nВектор:")
print(vector11)

print("\nМноження матриці на вектор:")
print(np.matmul(matrix11, vector11))

Матриця:
[[0.02761629 0.81103382 0.47128423]
 [0.29865892 0.17005915 0.11366266]]

Вектор:
[0.80549088 0.54539269 0.89961224]

Множення матриці на вектор:
[0.88854965 0.43556837]


In [ ]:
'''
12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими 
числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
'''

matrix12 = np.random.randint(1, 11, (2, 2))
matrix13 = np.random.randint(1, 11, (2, 2))

result = matrix12 * matrix13
print(matrix12)
print(matrix13)
print(result)

In [ ]:
'''
13. Створіть дві матриці розміром 2x2, заповніть їх випадковими 
цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
'''

a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

print(a)
print(b)

result = np.matmul(a, b)
print(result)

[[ 1 10]
 [ 4  8]]
[[6 2]
 [1 8]]
[[16 82]
 [32 72]]


In [32]:
'''
14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими 
числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
'''

a = np.random.randint(1, 101, (5, 5))

print(a)
print(np.sum(a)) 

[[48 38 68 56  9]
 [10 45 94 22 41]
 [21 50 78 57 54]
 [20  3 49 52 30]
 [81 76 94 46 30]]
1172


In [2]:
'''
15. Створіть дві матриці розміром 4x4, заповніть їх випадковими 
цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
'''
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))

print(a)
print(b)
print(a-b)

[[ 4  3  4  2]
 [10  3  4  1]
 [ 7  4  4  6]
 [ 6  7  3  2]]
[[ 7  9  2  9]
 [ 9  7  1  1]
 [ 3  2  5  6]
 [ 7 10  5  1]]
[[-3 -6  2 -7]
 [ 1 -4  3  0]
 [ 4  2 -1  0]
 [-1 -3 -2  1]]


In [6]:
'''
16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні 
від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
'''

a = np.random.rand(3, 3)
vector = a.sum(axis=1).reshape(-1, 1)

print('Матриця:')
print(a)
print('\nВектор:')
print(vector) 

Матриця:
[[0.6937997  0.67368364 0.93144542]
 [0.49371554 0.64874564 0.62087591]
 [0.79051934 0.88710603 0.81431145]]

Вектор:
[[2.29892876]
 [1.76333709]
 [2.49193681]]


In [9]:
'''
17. Створіть матрицю розміром 3x4 з довільними цілими 
числами і створіть матрицю з квадратами цих чисел.
'''

a = np.array([[14, 82, 78, 2],
              [16, 18,  8, 7],
              [3, 17, 17, 13]])

b = np.square(a)
print(b)

[[ 196 6724 6084    4]
 [ 256  324   64   49]
 [   9  289  289  169]]


In [16]:
'''
18. Створіть вектор розміром 4, заповніть його випадковими цілими числами 
в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
'''

vector = np.random.randint(1, 51, 4)
print(vector)

squared_vector = np.square(vector)
print(squared_vector)

[ 9 48 33  6]
[  81 2304 1089   36]
